### ISSUE TITLE
QC - Convert Efficiency Section's graph to be a histogram

### ISSUE THREAD

**Issue by ErinCain** [SRJPE/rst-pilot-app-client#236]
Check under the QC section's "Catch" & "Measured Variables & Associated Categories" for reference

Efficiency section graph should have - density line of historical efficiency in the background 
Overlay point plot of non QC records - point plot should have y = 0 or 1 (see what looks better) x should be calculated efficiency based on recaps/releases. [Points should be clickable / Editable in same way lollipop plots are working

Label x axis - Efficiency (Recaptured/Released), Label y axis - Density.

**Comment by Hunner4D** [comment]
From #246 
- [x] ensure data is being updated and qcCompleted being set (test UI, server, and verify on database)
