### ISSUE TITLE
QC Development Build Out Finalization

### ISSUE THREAD

**Issue by JordanHoang** [SRJPE/rst-pilot-app-client#323]
### Measured Variables

- [x] Y axis label overlapping y axis values

- [x] Weight y axis label is wrong

- [x] density graphs are not populating data in the modal. Showing “NA”
![Screenshot 2024-06-03 at 11 12 25 AM](https://github.com/SRJPE/rst-pilot-app-client/assets/22649273/1f20608a-17e1-4252-bf43-2bcaf4f9fe9c)

### Total Fish Count

- [x] Modal input needs to be correctly implemented. The input is hardcoded to testing and you can’t type anything else
![Screenshot 2024-06-03 at 11 14 35 AM](https://github.com/SRJPE/rst-pilot-app-client/assets/22649273/7646d2ba-8eb0-4159-8a86-6e70588aa870)

- [x] Y axis label overlapping y axis values

### QC Total Daily Count

- [x] Species dropdown at the top. Selection of this will filter data to build QC data for graph
- [x] Y value = sum of all measured records and plus counts for a species + dates
- [x] Only edit the plus count record

### Partial Records

- [x] Styling of table. Columns are misaligned
![Screenshot 2024-06-03 at 3 00 26 PM](https://github.com/SRJPE/rst-pilot-app-client/assets/22649273/25aa79f0-2033-4483-ad09-ab525c7d3a58)

- [x] Truncate values that push rows
- [x] Comment button no function
- [x] Ensure values are correctly formatted and using lookup names, rather than IDs (Run, Lifestage, etc)

### General

- [x] Increase modal height so fields aren't cut off
- [x] Make sure this is happening on all the ones with tables (various modals are being cut off)
- [x] Center and stretch table to include margin on both sides
- [x] Fork length input error
- [ ] How to handle graph anomalies (ex. 20,000 while avg. is under 1000)

- [x] Edit select not resetting selected value. Edit select options do not reset the selected value on save/close’
See this slack video I sent for what is happening: https://flowwest.slack.com/files/U019AEQ46HL/F073W1K0PJB/screen_recording_2024-05-20_at_4.17.44_pm.mov

**Comment by JordanHoang** [comment]
- [x] Crew still uses placeholder
![Screenshot 2024-07-03 at 11 53 01 AM](https://github.com/SRJPE/rst-pilot-app-client/assets/22649273/4deda7d4-d3f5-44f2-882c-5e055f1a9a22)

- [x] X axis doesn't match. What are we trying to convey for this graph? 
- - should behave simiarlty as Adipose Clipped but obviously Mortalities
- - Y Axis should be True / False, and X axis should be Date

![Screenshot 2024-07-03 at 11 56 25 AM](https://github.com/SRJPE/rst-pilot-app-client/assets/22649273/481f54d2-e60e-4ee0-b3a3-2c7f6070853c)

**Comment by JordanHoang** [comment]
- [x] labels still overlapping

![Screenshot 2024-07-03 at 11 51 40 AM](https://github.com/SRJPE/rst-pilot-app-client/assets/22649273/7a971629-24d7-43c5-b24f-4a5548a556e8)
![Screenshot 2024-07-03 at 11 57 21 AM](https://github.com/SRJPE/rst-pilot-app-client/assets/22649273/38f3adde-d727-45f5-859a-8d5c2efd2219)

**Comment by JordanHoang** [comment]
- [x] Label text wrapping

<img width="471" alt="Screenshot 2024-07-03 at 11 49 32 AM" src="https://github.com/SRJPE/rst-pilot-app-client/assets/22649273/4a15c19b-310e-4f29-ad46-03af9989dd5c">

**Comment by Hunner4D** [comment]
- [x] Find solution for squished graphs, x-axis labels could squish
    - [x] Test with x-scrollable graphs, maybe find buffer room or set bounds for graph pre-scroll

- [x] Orient graphs to display in order of buttons displayed at top of screen
    - [x] Applies to several pages

- [x] NestedModals
    - [x] Add trap visit information to nested modals
    - [x] Dates, trap visit info, trap site, stream name, general

- [x] Adjust red color on graphs to be lighter, modern
- [x] Remove values from density graph x-axis’s

- [x] QC Measure
    - [x] Date range would be very helpful to graphs to know when
    - [x] Differentiate points by Lifestage by color
    - [x] Say historic data is showed in density line
    - [x] Remove data points after QC
    - [x] Should have a legend for the lifestage colors

- [x] QC Categorical
    - [x] Adipose clipped x-axis change to date collected

- [x] Keep true/false’s as true/false, not yes/no
- [x] Keep graph point coloring consistent between graphs (qcCompleted)
- [x] Adipose clipped QCcategorical input not toggling
- [x] Graph dot size consistency 

- [x] QCcategorical
    - [x] Remove species plot from 
    - [x] Not getting mark type from marks graph
    - [x] Change shapes to dots

- [x] QC Total Daily count
    - [x] Edit numeric input to say edit plus count

- [x] Partial Records
    - [x] Add species to editing table
    - [x] Change taxon to species
    - [x] Comment button on partial records

- [x] Discuss how to populate staging DB for qc data for Ashely and liz

**Comment by JordanHoang** [comment]
Flag button doesn't do anything. What to do?

**Comment by JordanHoang** [comment]
how to handle no data for a chart (currently populates weird values for x and y axis)

- [x] display no chart if species not selected for total daily count

- [ ]  do not show X or Y axis tick values if no data
- [x] add messaging to indicate no data available

**Comment by Hunner4D** [comment]
> * [x]  Crew still uses placeholder
>   ![Screenshot 2024-07-03 at 11 53 01 AM](https://private-user-images.githubusercontent.com/22649273/345535980-4deda7d4-d3f5-44f2-882c-5e055f1a9a22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjAxNDEsIm5iZiI6MTcyMTA1OTg0MSwicGF0aCI6Ii8yMjY0OTI3My8zNDU1MzU5ODAtNGRlZGE3ZDQtZDNmNS00NGYyLTg4MmMtNWUwNTVmMWE5YTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE2MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMGU5NDBmOTg4NjJiNTY4NGIwMDkzZjg0NjJiMjRhMmNmNzIwNTdmOThhZmJhODNkOGQ5NTE5NjlhZTU3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IElurUhC1ehMn4TCZgppFIIMoRqe-boZVQPMYIPRXUg)

Should this be release_crew or trap_visit_crew

**Comment by JordanHoang** [comment]
> > * [x]   Crew still uses placeholder
> >   ![Screenshot 2024-07-03 at 11 53 01 AM](https://private-user-images.githubusercontent.com/22649273/345535980-4deda7d4-d3f5-44f2-882c-5e055f1a9a22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjAxNDEsIm5iZiI6MTcyMTA1OTg0MSwicGF0aCI6Ii8yMjY0OTI3My8zNDU1MzU5ODAtNGRlZGE3ZDQtZDNmNS00NGYyLTg4MmMtNWUwNTVmMWE5YTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE2MTA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMGU5NDBmOTg4NjJiNTY4NGIwMDkzZjg0NjJiMjRhMmNmNzIwNTdmOThhZmJhODNkOGQ5NTE5NjlhZTU3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IElurUhC1ehMn4TCZgppFIIMoRqe-boZVQPMYIPRXUg)
> 
> Should this be release_crew or trap_visit_crew

trap_visit crew

@Hunner4D

**Comment by Hunner4D** [comment]
- [x] Wire qc submission posting to all aprove buttons on all QC pages

**Comment by JordanHoang** [comment]
Notes from 7/30 @Hunner4D 

- [x] Use set list of colors for all legends: 
#007C7C
#F9A38C
#D1E8F0
#011936
#564e58
#846075
#2b3a67
#772E25
#FBA72A
#C0CAAD

- [x] X Axis labels are squished 
- [x] Change “Approve” on QC pages to Save  (can leave as Approve on Modals)
- [x] Intermediate step from not QC’d to QC’d to Saved
- [x] Make FL and weight buttons longer so they are one line
- [x] Make legend values horizontal or move legend to the right side
- [x] show multiple points if points are overlayed for AD clipped and Morts
- [x] Add description that this is only intended to edit plus count 
- [x] Mark Type partial records bug
- [x] Adipose clipped column is missing from Partial Records as well as others. make sure consistent
- [x] Efficiency Data - build out and complete
- [x] If plus count sum comes from multiple combos of life stage and run need to break it down [TBD Jordan]
- - Table of multiple fish with variables Species, Life Stage, Run, Plus Count
- [ ] Mark all column records as a certain value - NA vs false vs not recorded [tbd Jordan]

**Comment by JordanHoang** [comment]
- [x] Mark Type value from table is not making it to Edit Modal
