### ISSUE TITLE
Authentication Build Out Finalization

### ISSUE THREAD

**Issue by JordanHoang** [SRJPE/rst-pilot-app-client#324]
**Retrieving User Information**
- [x] retrieve user info from backend on succesful login
- [x] filter dropdown values based on user program

**Remove Hardcoding**
- [x] no hardcoded program values for retrieving and displaying data. Should be using signed in user's program
- [x] no hardcoded program values for conditionally rendering the UI. Should be using signed in user's program
- [ ] #329

**Creating User**

- [x] Post User to Azure DB
- [x] Add new user to server DB
- [x] Restrict permission to users designated as **Lead**

** Miscellaneous **

- [ ] #330
-- For catchRawSubmissions, src/screens/formScreens/IncompleteSections.tsx line 493
-- see where we are using createdBy

**Comment by Hunner4D** [comment]
On ProgramQC.tsx there is a hard-coded value as _userPrograms_ at line 14
On trapVisitFormPostBundler, there is a hard-coded value as _programIds_ at line 232
